name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          working-directory: ./hello

      - name: Install dependencies
        run: npm install
        working-directory: ./hello

      - name: Build React application
        run: npm run build
        working-directory: ./hello

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }} # シークレットとして設定したトークンを使用
          branch: gh-pages
          folder: ./hello/build # ビルド出力フォルダに合わせて修正
          repository-name: ${{ github.repository }}
          # user-name: ${{ github.event.pusher.name }} # 不要
          # user-email: ${{ github.event.pusher.email }} # 不要
